version: '3.0'

services:
  creek-producer:
    build:
      dockerfile: Dockerfile.dev
      context: .
      args:
        UID: ${UID}
        USER: ${USER}
    environment:
      PG_URI: ""
      PG_PUBLICATION_NAME: creek_pub
      PG_PUBLICATION_SLOT: creek_slot
      PG_TABLES: public.fx_sek
      NATS_URI: nats://nats:4222
      NATS_NAMESPACE: CREEK
      NATS_MAX_PENDING: 4000
      NATS_TIMEOUT: 30s
    volumes:
      - .:/creek
      - gopkg-creek:/go/pkg
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "7779:7779"

  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--http_port 8222 -js"

  nats-exporter:
    image: natsio/prometheus-nats-exporter:0.16.0
    ports:
      - "7777:7777"
    command: "-varz -healthz -connz -jsz=all http://nats:8222"
    depends_on:
      - nats

  prometheus:
    image: prom/prometheus
    volumes:
      - .supporting/prometheus:/etc/prometheus
      - prom_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - .supporting/grafana/datasources:/etc/grafana/provisioning/datasources
      - .supporting/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - .supporting/grafana/dashboards:/var/lib/grafana/dashboards



volumes:
  prom_data:
  producer_data:
  gopkg-creek: