FROM golang:1.20-alpine as builder

COPY . /go/src/creek
WORKDIR /go/src/creek

RUN go mod download
RUN go build -o /creekd cmd/creekd.go

FROM alpine
COPY --from=builder /creekd /
ENTRYPOINT [ "/creekd" ]