FROM golang:1.24

RUN apt-get update && apt-get install -y inotify-hookable
RUN go install github.com/codeskyblue/fswatch@latest

RUN mkdir -p /creek
WORKDIR /creek

EXPOSE 7779

# run fswatch
CMD cd /creek && fswatch -config /fsw.yml
