FROM golang:1.24-alpine as builder

COPY . /creek
WORKDIR /creek

RUN go mod download
RUN go build -o /creekd cmd/creekd.go

FROM --platform=linux/amd64 alpine:3.21.3

COPY --from=builder /creekd /
ENTRYPOINT [ "/creekd" ]