desc: re builds go
triggers:
  - name: ''
    pattens:
      - '**/*.go'
      - '**/*.html'
      - '**/*.css'
      - './api.yaml'
      - '!**/*_test.go'
    env:
      DEBUG: '1'
    cmd: go run ./cmd/creekd.go
    shell: true
    delay: 100ms
    stop_timeout: 500ms
    signal: KILL
    kill_signal: 'SIGTERM'
watch_paths:
  - .
watch_depth: 10