{
 "title": "Creek",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source table", "query": { "query": "label_values(creek_pg_source)" } },
   {
    "name": "type",
    "label": "message type",
    "query": {
     "query": "label_values(creek_stream_type)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Producers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Producer events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by(creek_pg_source) (rate(creek_producer_pg_reads{creek_pg_source=~\"$source\", creek_stream_type=~\"$type\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "WAL behind bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "creek_producer_pg_behind_bytes" }
   ]
  },
  {
   "title": "WAL time behind",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "creek_producer_pg_behind_time" }
   ]
  },
  { "title": "Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "DB updates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(creek_consumer_pg_inserts{creek_pg_source=~\"$source\", creek_stream_type=~\"$type\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Snapshot rows read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(creek_pg_source, instance) (creek_consumer_pg_inserts{creek_stream_type=\"snap\"})"
    }
   ]
  }
 ]
}