FROM postgres:13 as builder

ADD docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

RUN ["sed", "-i", "s/exec \"$@\"/echo \"skipping...\"/", "/usr/local/bin/docker-entrypoint.sh"]

ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=qwerty
ENV PGDATA=/data

RUN ["/usr/local/bin/docker-entrypoint.sh", "postgres"]

FROM postgres:13

COPY --from=builder /data $PGDATA