global:
  scrape_interval:     5s # By default, scrape targets every 5 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'nats-integration_tests-server'

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'nats-integration_tests-server'

    static_configs:
      - targets: ['nats-exporter:7777', 'creek-pg-client:7778', 'creek-producer:7779']
